# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[97;9u"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[114;9u"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[115;9u"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[116;9u"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C"
key = "Backslash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[48;9u"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[49;9u"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[50;9u"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[51;9u"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[52;9u"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[53;9u"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[54;9u"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[55;9u"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[56;9u"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[57;9u"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[102;9u"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[103;9u"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[104;9u"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[106;9u"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[107;9u"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[108;9u"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[119;9u"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[92;9u"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[59;9u"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "None"
dynamic_padding = true
opacity = 1
option_as_alt = "Both"

[cursor.style]
blinking = "Never"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
