[indicator]
padding = { open = "█", close = "█" }

[mgr]
cwd = { fg = "#ebdbb2", italic = true }

# Find
find_keyword  = { fg = "#1b1b1b", bg = "#fe8019", bold = true }
find_position = { fg = "#8ec07c", bg = "#3c3836", bold = true }

# Marker
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }
marker_marked   = { fg = "#d3869b", bg = "#d3869b" }
marker_selected = { fg = "#83a598", bg = "#83a598" }

# Count
count_copied   = { fg = "#1b1b1b", bg = "#b8bb26" }
count_cut      = { fg = "#1b1b1b", bg = "#fb4934" }
count_selected = { fg = "#1b1b1b", bg = "#83a598" }

# Border
border_symbol = "│"
border_style  = { fg = "#8ec07c" }

# Tab
[tabs]
active   = { fg = "#1b1b1b", bg = "#83a598" }
inactive = { fg = "#83a598", bg = "#3c3836" }

[mode]
normal_main = { fg = "#1b1b1b", bg = "#83a598", bold = true }
normal_alt  = { fg = "#83a598", bg = "#3c3836" }

select_main = { fg = "#1b1b1b", bg = "#d3869b", bold = true }
select_alt  = { fg = "#d3869b", bg = "#3c3836" }

unset_main  = { fg = "#1b1b1b", bg = "#d3869b", bold = true }
unset_alt   = { fg = "#d3869b", bg = "#3c3836" }

[status]
overall   = { fg = "#ebdbb2", bg = "#1b1b1b" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#458588", bg = "#282828" }
progress_error  = { fg = "#fb4934", bg = "#282828" }

# Permissions
perm_type  = { fg = "#83a598" }
perm_read  = { fg = "#fabd2f" }
perm_write = { fg = "#fb4934" }
perm_exec  = { fg = "#b8bb26" }
perm_sep   = { fg = "#504945" }

[pick]
border   = { fg = "#8ec07c" }
active   = { fg = "#ebdbb2",  bg = "#3c3836" }
inactive = { fg = "#ebdbb2" }

# Input
[input]
border   = { fg = "#8ec07c" }
title    = { fg = "#8ec07c" }
value    = { fg = "#d3869b" }
selected = { bg = "#3c3836" }

# Completion
[cmp]
border   = { fg = "#8ec07c" }
active   = { fg = "#ebdbb2", bg = "#3c3836" }
inactive = { fg = "#ebdbb2" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#8ec07c" }
title   = { fg = "#8ec07c" }
hovered = { fg = "#ebdbb2", bg = "#3c3836" }

# Which
[which]
cols            = 3
mask            = { bg = "#1b1b1b" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#83a598" }
desc            = { fg = "#d3869b" }
separator       = " ➜ "
separator_style = { fg = "#928374" }

# Confirm
[confirm]
border  = { fg = "#8ec07c" }
title   = { fg = "#8ec07c" }
content = {}
list    = {}
btn_yes = { bg = "#3c3836" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#8ec07c" }
title   = { fg = "#8ec07c" }

# Notify
[notify]
title_info  = { fg = "#8ec07c" }
title_warn  = { fg = "#fabd2f" }
title_error = { fg = "#fb4934" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#b8bb26" }
run     = { fg = "#d3869b" }
desc    = { fg = "#8ec07c" }
hovered = { bg = "#282828" }
footer  = { fg = "#ebdbb2", bg = "#1b1b1b" }

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#fabd2f" },
	# Media
	{ mime = "{audio,video}/*", fg = "#d3869b" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fb4934" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#8ec07c" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#ebdbb2" },
	# Special file
	{ url = "*", is = "orphan", bg = "#fb4934" },
	{ url = "*", is = "exec"  , fg = "#b8bb26" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "#ebdbb2" },
	{ url = "*/", is = "dummy", bg = "#83a598" },
	# Fallback
	{ url = "*/", fg = "#83a598" }
]
